version: '3'
services:
  mongo:
    image: mongo:3.6
    ports:
      - "27017:27017"
    volumes:
      - ./company-mortgages-data.js:/docker-entrypoint-initdb.d/company-mortgages-data.js
    environment:
      - MONGO_INITDB_DATABASE=company_mortgages
#  charges-data-api:
#    image: charges-data-api:latest
#    ports:
#      - "18576:18576"
#    environment:
#      - LOGGING_LEVEL=DEBUG
#      - MONGODB_URL=mongodb://mongo:27017/company_mortgages