server:
  port : 8081

logger:
  namespace: charges-data-api

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:localhost}
      key: ${CHS_INTERNAL_API_KEY:chsInternalApiKey}

spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/company_mortgages?retryWrites=false}
      name: company_mortgages

mongodb:
  charges:
    collection:
      name: ${CHARGES_COLLECTION_NAME:company_mortgages}

charges:
  api:
    resource:
      changed:
        uri: ${CHARGES_API_RESOURCE_CHANGED_URI:/resource-changed}
      kind: ${CHARGES_API_RESOURCE_KIND:company-charges}

api:
  company:
    metrics:
        endpoint: ${COMPANY_METRICS_API_URL:https://localhost}
        key: ${COMPANY_METRICS_API_KEY:apiKey}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: never
      enabled: true