server:
  port : 8089

logger:
  namespace: charges-data-api

chs:
  kafka:
    api:
      endpoint: ${CHS_KAFKA_API_URL:http://localhost:8888}
      key: ${CHS_INTERNAL_API_KEY:chsInternalApiKey}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://0.0.0.0:27017/company-mortgages?retryWrites=false}
      name: company-mortgages

mongodb:
  charges:
    collection:
      name: ${CHARGES_COLLECTION_NAME:company_mortgages}

charges:
  api:
    resource:
      changed:
        uri: ${CHARGES_API_RESOURCE_CHANGED_URI:/private/resource-changed}
      kind: ${CHARGES_API_RESOURCE_KIND:company-charges}

api:
  company:
    metrics:
        endpoint: ${COMPANY_METRICS_API_URL:http://localhost:8888}
        key: ${COMPANY_METRICS_API_KEY:apiKey}